### DISCUSSION TITLE
Dependabot grouped updates

### DISCUSSION THREAD

**Discussion by Pliner** [encode/httpcore#792] [Ideas]
Hey,

Using grouped updates could help to reduce noise produced by Dependabot (many PRs, many notifications) and reduce efforts needed (no need to approve PRs individually and so on). 

https://github.blog/changelog/2023-06-30-grouped-version-updates-for-dependabot-public-beta/

The simplest configuration might look like this.

```
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      packages:
        patterns:
          - "*"
```

Of course, dependencies might be split to multiple groups (dev dependencies like linters/docs and release ones).
